### PR TITLE
Ensure module completes without error if re-runinng against an eradicated volume

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
Ensure rerunning a playbook against an eradicated volume doesn't fail

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
purefa_volume.py

### CODE REVIEW

**Comment by dnix101** [comment]
If I run the following playbook, the second task, still returns an error that the Size must be specified:

```
    - name: My first task
      purefa_volume:
        name: remko_test
        state: present
        size: 100G
        fa_url: "{{ fa1_url }}"
        api_token: "{{ fa1_api_token }}"

    - name: My delete 1 task
      purefa_volume:
        name: remko_test
        state: absent
        eradicate: true
        fa_url: "{{ fa1_url }}"
        api_token: "{{ fa1_api_token }}"

    - name: My delete 2 task
      purefa_volume:
        name: remko_test
        state: present
        eradicate: true
        fa_url: "{{ fa1_url }}"
        api_token: "{{ fa1_api_token }}"
    - pause:
        prompt: "Press key to continue"
```

This is the debug info:

```
TASK [My delete 2 task] ***********************************************************************************************************************
task path: /home/rdeenik/ansible-fa/eradicate_idempotency/test_eradicate_idempotency.yml:29
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: rdeenik
<127.0.0.1> EXEC /bin/sh -c 'echo ~rdeenik && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/rdeenik/.ansible/tmp `"&& mkdir /home/rdeenik/.ansible/tmp/ansible-tmp-1600541117.7-15249-269532150892951 && echo ansible-tmp-1600541117.7-15249-269532150892951="` echo /home/rdeenik/.ansible/tmp/ansible-tmp-1600541117.7-15249-269532150892951 `" ) && sleep 0'
Using module file /home/rdeenik/.ansible/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_volume.py
<127.0.0.1> PUT /home/rdeenik/.ansible/tmp/ansible-local-151348Mow9t/tmprxK2rp TO /home/rdeenik/.ansible/tmp/ansible-tmp-1600541117.7-15249-269532150892951/AnsiballZ_purefa_volume.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/rdeenik/.ansible/tmp/ansible-tmp-1600541117.7-15249-269532150892951/ /home/rdeenik/.ansible/tmp/ansible-tmp-1600541117.7-15249-269532150892951/AnsiballZ_purefa_volume.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/rdeenik/.ansible/tmp/ansible-tmp-1600541117.7-15249-269532150892951/AnsiballZ_purefa_volume.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/rdeenik/.ansible/tmp/ansible-tmp-1600541117.7-15249-269532150892951/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "bw_qos": null, 
            "eradicate": true, 
            "fa_url": "10.225.112.80", 
            "iops_qos": null, 
            "move": null, 
            "name": "remko_test", 
            "overwrite": false, 
            "rename": null, 
            "size": null, 
            "state": "present", 
            "target": null
        }
    }, 
    "msg": "Size must be specified to create a new volume"
}
```

**Comment by sdodsley** [comment]
@dnix101 that is expected. Your first deletion and eradicate completes so there is nothing left. The second delete actually say `state: present` so you are effectively creating a new volume, which needs `size`

**Comment by dnix101** [comment]
Ah my bad! I had ment for the second to be a delete too to test idempotency. I'll approve.

**Review by dnix101 — APPROVED** [review]
shipit

**Pull request merged**
