### PR TITLE
Add multi-volume creation support (Purity 6.0+)

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
From Purity 6 we can now create multi-volumes with a single call.

Required information is the number of volumes to create, the index start point and the index character size. Name suffix after index is also supported.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
purefa_volume.py

##### ADDITIONAL INFORMATION
New parameters:
 * **count** - Number of volumes to create (Required)
 * **digits** - Size of index string - will pad with zeros where necessary (Default = 1)
 * **start** - Start number for volume index (Default = 0)
 * **suffix** - String to append to volume name and index

The volumes created will have the name format: _name#suffix_ where # is the volume index number

**!! NOTE !!**
 * Only volume creation is supported by multi-volume at this time.
 * If a multi-volume created volume is deleted or eradicated from the sequence he idempotency of the creation task will fail

### CODE REVIEW

**Review by dnix101 — CHANGES_REQUESTED** [review]
Two comments:
- Creation of multiple volumes in a POD or VG returns errors
- It would be nice if the module would return the name, size, serial, etc of the volumes as output, so that you can `register` the output and use that in the rest of the playbook. When creating a single vol this information is being returned by the module.

**Comment by sdodsley** [comment]
@dnix101 Let me check the pod and VG errors.
As to the output - unfortunately, the REST response is not in a form that enables us to match volume with size and serial number

**Comment by dnix101** [comment]
> @dnix101 Let me check the pod and VG errors.
> As to the output - unfortunately, the REST response is not in a form that enables us to match volume with size and serial number

Any chance we can at least return the names?

**Comment by sdodsley** [comment]
Not really - it all just comes out as a string of values with no correlation between them. I'll see if there is anything I can produce

**Comment by sdodsley** [comment]
@dnix101 Pods and VGs now work and you also get the same return from multi-volume creation as you do from a single volume

**Review by dnix101 — APPROVED** [review]
Perfect, shipit!

**Pull request merged**
