### PR TITLE
Fix IPv6 and IPv4 issues for subnet and network modules

### LINKED ISSUE #466: some issues regarding purefa_network and purefa_subnet
My customer is testing ansible environment for production use, and found some issues.
Could you please fix these?

- purefa_network
01.configure IPv6 address or gateway
02.change IPv6 address or gateway
03.delete IPv6 address or gateway

- purefa_subnet
04.remove **IPv4** gateway
05.create IPv6 subnet
06.change IPv6 prefix or gateway

•             Ansible version: ansible [core 2.15.4]
•             FlashArray Collection version: 1.21.0
•             Purity version: 6.3.13
•             FlashArray module causing the failure: purefa_network and purefa_subnet
•             Name of the interface and the service(s) enabled on the interface: ct0.eth5
•             An example task that fails
•             Response from ansible-playbook -vvvv when running a failing task: see attached file

[01.log](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/12780683/01.log)
[02.log](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/12780684/02.log)
[03.log](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/12780685/03.log)
[04.log](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/12780686/04.log)
[05.log](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/12780687/05.log)
[06.log](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/12780688/06.log)

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
Addresses issues when using IPv6 address with [] and also removing an IPv4 gateway.
Address part of #466 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
purefa_subnet.py

### CODE REVIEW

**Comment by tylergmuir** [comment]
Fixes #472

**Comment by sdodsley** [comment]
Backed out changes to `purefa_network. These have been rolled into #474

**Comment by ryuyamag** [comment]
I checked these patches.

purefa_subnet.py works fine.
but purefa_network.py seems didn't work correctly with ipv4&ipv6.
please take a look at the attached logs.

[network.zip](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/12798500/network.zip)

**Comment by sdodsley** [comment]
I will address the outstanding issues in #474

**Pull request merged**
