### PR TITLE
Add DNS check_peer and cert upload to DNS

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
Add `certificate` and `check_peer` parameters for management DNS entry.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
purefa_dns.py

### CODE REVIEW

**Comment by ryuyamag** [comment]
Sorry for the late reply.
I got the error attached.
[purefa_ds_cert.yml.zip](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/13456425/purefa_ds_cert.yml.zip)

**Comment by sdodsley** [comment]
@ryuyamag Please try again. Stupid typo now fixed.

**Comment by ryuyamag** [comment]
Thank you for quick response!
This worked fine.

By the way, Is it difficult to clear the cert? If that is difficult, I encourage customers to use a dummy text.

**Comment by sdodsley** [comment]
To clear the cert just empty an empty string, eg:
`certificate: ""`

**Comment by ryuyamag** [comment]
I think I'll go with 3.

1.""
it didn't work. The cert remained the same.

2." "
following error message appeared.
"msg": "Management Directory Service failed. Error message: Invalid certificate data."

3.
So, I was able to replace it by specifying the following text file.
-----BEGIN CERTIFICATE------
dummy data
-----END CERTIFICATE----

**Pull request merged**
