### PR TITLE
Assume gateway could be empty in pure

### PR DESCRIPTION
**Pull request by jruariveiro**
##### SUMMARY

Configuring flasharray networking fails when gateway is not setup in pure.

When you don't pass gateway to purefa_network module it will use what's available
in pure device. If this is empty, then it fails. 

##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

purefa_network

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by sdodsley** [comment]
@jruariveiro Your PR must pass all the CI tests before we will look at it.

**Comment by jruariveiro** [comment]
Well done, folks

**Comment by sdodsley** [comment]
@jruariveiro Please sign the CLA for this so we can merge the PR

**Comment by jruariveiro** [comment]
Done!

**Pull request merged**
