### PR TITLE
Fix netaddr compatability issue

### LINKED ISSUE #629: Issue with IP configuration using purefa_network and netaddr compatibility
I am currently attempting to configure IP addresses using the purefa_network playbook, but I have encountered an issue related to the version of the netaddr module. Specifically, when using netaddr versions 1.2.0 or 1.3.0, errors occur during execution, whereas version 1.1.0 does not cause any problems.

Ansible version : core 2.15.8
FlashArray Collection version: 1.31.1
Purity version: 6.6.7
FlashArray module causing the failure: purefa_network
An example task that fails: set or remove ipaddr/mask/gateway 
Response from ansible-playbook -vvvv when running a failing task

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.229.192.60'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings\n  warnings.warn(\n/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.229.192.60'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings\n  warnings.warn(\n/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.229.192.60'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings\n  warnings.warn(\n/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.229.192.60'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings\n  warnings.warn(\n/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.229.192.60'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings\n  warnings.warn(\n/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.229.192.60'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings\n  warnings.warn(\n/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.229.192.60'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings\n  warnings.warn(\n/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.229.192.60'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings\n  warnings.warn(\n/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.229.192.60'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings\n  warnings.warn(\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1725709231.220546-56982-269451338359497/AnsiballZ_purefa_network.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1725709231.220546-56982-269451338359497/AnsiballZ_purefa_network.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1725709231.220546-56982-269451338359497/AnsiballZ_purefa_network.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_network', init_globals=dict(_module_fqn='ansible_collections.purestorage.flasharray.plugins.modules.purefa_network', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_purestorage.flasharray.purefa_network_payload_e1og9so3/ansible_purestorage.flasharray.purefa_network_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_network.py\", line 790, in <module>\n  File \"/tmp/ansible_purestorage.flasharray.purefa_network_payload_e1og9so3/ansible_purestorage.flasharray.purefa_network_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_network.py\", line 760, in main\n  File \"/tmp/ansible_purestorage.flasharray.purefa_network_payload_e1og9so3/ansible_purestorage.flasharray.purefa_network_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_network.py\", line 352, in update_interface\n  File \"/usr/local/lib/python3.9/site-packages/netaddr/strategy/ipv4.py\", line 99, in valid_str\n    raise TypeError('Invalid type: %s' % type(addr))\nTypeError: Invalid type: <class 'NoneType'>\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
Fix compatibility issue with `netaddr>=1.2.0`
Update requirements for `netaddr`
Remove `mtu` default setting. Let the FA tell you what the current/default setting should be.
Closes #629 

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
purefa_network.py
README.md
requirements.txt

### CODE REVIEW

**Comment by ryuyamag** [comment]
Thank you for the module fix. Upon testing, I found that the issue regarding setting the address has been resolved without any problems.

However, when attempting to delete the address, the following issues were encountered. Could you kindly investigate further?

**For IPv6:** 
The address was successfully deleted, but the netmask was not cleared.

**For IPv4:**
The following error occurred.
 
```
task path: /etc/ansible/network/purefa_network_deladdress_ipv4.yml:4
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1726120851.5060875-64699-8283054654824 `" && echo ansible-tmp-1726120851.5060875-64699-8283054654824="` echo /root/.ansible/tmp/ansible-tmp-1726120851.5060875-64699-8283054654824 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_network.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-64642xs2xrsjj/tmpnzx6s849 TO /root/.ansible/tmp/ansible-tmp-1726120851.5060875-64699-8283054654824/AnsiballZ_purefa_network.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1726120851.5060875-64699-8283054654824/ /root/.ansible/tmp/ansible-tmp-1726120851.5060875-64699-8283054654824/AnsiballZ_purefa_network.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1726120851.5060875-64699-8283054654824/AnsiballZ_purefa_network.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1726120851.5060875-64699-8283054654824/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_purestorage.flasharray.purefa_network_payload_nmu_jgf7/ansible_purestorage.flasharray.purefa_network_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_network.py", line 498, in update_interface
  File "/usr/local/lib/python3.9/site-packages/purestorage/purestorage.py", line 1531, in set_network_interface
    return self._request("PUT", "network/{0}".format(interface), kwargs)
  File "/usr/local/lib/python3.9/site-packages/purestorage/purestorage.py", line 202, in _request
    raise PureHTTPError(self._target, str(self._rest_version), response)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "address": "0.0.0.0/0",
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "disable_warnings": false,
            "enabled": true,
            "fa_url": "10.229.192.60",
            "gateway": "0.0.0.0",
            "interface": null,
            "mtu": 1500,
            "name": "ct0.eth2",
            "servicelist": null,
            "state": "present",
            "subinterfaces": null,
            "subnet": null,
            "subordinates": null
        }
    },
    "msg": "Failed to change settings for interface ct0.eth2."
}
```

**Comment by sdodsley** [comment]
@ryuyamag the error you posted doesn't seem to match the current codebase. Line 498 doesn't call set_network_interfaces.
Can you confirm you are using this patched version of the code?

**Comment by ryuyamag** [comment]
@sdodsley 
I think I am using the following commit:
commit 9054829e632baaa752ea55b619f6b792d609e2a7

Please confirm if this is the correct version for the fix. I apologize if I am mistaken.

```
The full traceback is:
  File "/tmp/ansible_purestorage.flasharray.purefa_network_payload_wxd_skhc/ansible_purestorage.flasharray.purefa_network_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_network.py", line 498, in update_interface
  File "/usr/local/lib/python3.9/site-packages/purestorage/purestorage.py", line 1531, in set_network_interface
    return self._request("PUT", "network/{0}".format(interface), kwargs)
  File "/usr/local/lib/python3.9/site-packages/purestorage/purestorage.py", line 202, in _request
    raise PureHTTPError(self._target, str(self._rest_version), response)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "address": "0.0.0.0/0",
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "disable_warnings": false,
            "enabled": true,
            "fa_url": "10.229.192.60",
            "gateway": "0.0.0.0",
            "interface": null,
            "mtu": 1500,
            "name": "ct0.eth2",
            "servicelist": null,
            "state": "present",
            "subinterfaces": null,
            "subnet": null,
            "subordinates": null
        }
    },
    "msg": "Failed to change settings for interface ct0.eth2."
}

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

[root@ryamag-ansible network]# cd /root/.ansible/collections/ansible_collections/purestorage/flasharray/plugins/modules
[root@ryamag-ansible modules]# diff purefa_network.py old_purefa_network.py.20240912a
351,355c351,356
<         if interface["address"] and valid_ipv4(interface["address"]):
<             current_state["gateway"] = None
<         elif interface["address"] and valid_ipv6(interface["address"]):
<             current_state["gateway"] = None
<         else:
---
>         try:
>             if valid_ipv4(interface["address"]):
>                 current_state["gateway"] = None
>             elif valid_ipv6(interface["address"]):
>                 current_state["gateway"] = None
>         except AttributeError:
[root@ryamag-ansible modules]#
```

**Comment by sdodsley** [comment]
@ryuyamag can you try this again? I think I have it. This module is very complex and there are lots of areas where different functions overlap.
The netmask should also be cleared correctly as well now for both IPv4 and IPv6

**Pull request merged**
