### PR TITLE
Fix scheduling update issues

### LINKED ISSUE #481: purefa_pgsched can't set "snap_at" or "replicate_at" to 0
There are some cases not possible to update the schedule using purefa_pgsched.
For example, set the schedule in PG as follows
    snap_frequency: 86400
    snap_at: 15:30:00

Then I can't change it to the following settings.
    snap_frequency: 86400
    snap_at: 0

    snap_frequency: 3600
    snap_at: 0
    
• Ansible version: ansible [core 2.15.5]
• FlashArray Collection version: 1.21.0
• Purity version: 6.3.13
• FlashArray module causing the failure: purefa_pgsched

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
`snap_at` and `replicate_at` where incorrectly asking for 24-hour time with minutes and seconds. Should only request an hourly time in AM or PM.
Fix issue if AM or PM is lowercase.
Fix issue when changing from daily schedule to hourly schedule.
Fixes #481 

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
purefa_pgsched.py

### CODE REVIEW

**Comment by ryuyamag** [comment]
Thank you for your quick response.

"snap_at" was fine.
"replicate_at" seems to have run into an error. I have attached the log.
Please take a look when you have time.
[20231016.zip](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/12915435/20231016.zip)

**Comment by sdodsley** [comment]
@ryuyamag my bad - typo - try this now

**Comment by ryuyamag** [comment]
I was getting a different error for 3f78a99.
Please check it when it is convenient for you.
[20231016b.zip](https://github.com/Pure-Storage-Ansible/FlashArray-Collection/files/12917123/20231016b.zip)

**Comment by sdodsley** [comment]
@ryuyamag That should be fixed now

**Comment by ryuyamag** [comment]
I have confirmed that this works properly. thank you.

**Pull request merged**
