### PR TITLE
Add support for renaming protection groups

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
Add `rename` option to allow rename of existing protection groups.
If the source PG is in a container such as a pod or volume group, eg `pod::pg` or `vg:pg`, then there's no
requirement to specify the container in the `rename` parameter.
Protection Groups cannot be renamed into different containers.

Also add in naming convention check for protection group name as part of create or rename PG

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
purefa_pg.py

### CODE REVIEW

**Review by genegr — APPROVED** [review]
shipit

**Comment by dnix101** [comment]
I get an error when trying to rename a volume in a Pod. I believe the error is related to line 738 where key `name` is used, which should have been `pgroup`. However even if that is changed, I don't see why it would fail the naming convention.

Playbook:
```
    - name: Rename pod PG
      purefa_pg:
        pgroup: "z-ProdPod::remko"
        rename: pgremko1
        fa_url: "{{ fa1_url }}"
        api_token: "{{ fa1_api_token }}"
```

Error:
```
TASK [Rename pod PG] *************************************************************************************************************************************
task path: /home/rdeenik/ansible-fa/rename_pg/test_rename_pg.yml:22
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: rdeenik
<127.0.0.1> EXEC /bin/sh -c 'echo ~rdeenik && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/rdeenik/.ansible/tmp `"&& mkdir "` echo /home/rdeenik/.ansible/tmp/ansible-tmp-1616495635.9846523-3288-158914007403594 `" && echo ansible-tmp-1616495635.9846523-3288-158914007403594="` echo /home/rdeenik/.ansible/tmp/ansible-tmp-1616495635.9846523-3288-158914007403594 `" ) && sleep 0'
Using module file /home/rdeenik/.ansible/collections/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py
<127.0.0.1> PUT /home/rdeenik/.ansible/tmp/ansible-local-31905qicf95a/tmpcwwvj945 TO /home/rdeenik/.ansible/tmp/ansible-tmp-1616495635.9846523-3288-158914007403594/AnsiballZ_purefa_pg.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/rdeenik/.ansible/tmp/ansible-tmp-1616495635.9846523-3288-158914007403594/ /home/rdeenik/.ansible/tmp/ansible-tmp-1616495635.9846523-3288-158914007403594/AnsiballZ_purefa_pg.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/rdeenik/.ansible/tmp/ansible-tmp-1616495635.9846523-3288-158914007403594/AnsiballZ_purefa_pg.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/rdeenik/.ansible/tmp/ansible-tmp-1616495635.9846523-3288-158914007403594/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/usr/lib/python3/dist-packages/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/lib/python3/dist-packages/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/lib/python3/dist-packages/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/home/rdeenik/.ansible/tmp/ansible-tmp-1616495635.9846523-3288-158914007403594/AnsiballZ_purefa_pg.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/rdeenik/.ansible/tmp/ansible-tmp-1616495635.9846523-3288-158914007403594/AnsiballZ_purefa_pg.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/rdeenik/.ansible/tmp/ansible-tmp-1616495635.9846523-3288-158914007403594/AnsiballZ_purefa_pg.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.purestorage.flasharray.plugins.modules.purefa_pg', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_purefa_pg_payload_8v9uidr1/ansible_purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py\", line 795, in <module>\n  File \"/tmp/ansible_purefa_pg_payload_8v9uidr1/ansible_purefa_pg_payload.zip/ansible_collections/purestorage/flasharray/plugins/modules/purefa_pg.py\", line 738, in main\nKeyError: 'name'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by sdodsley** [comment]
@dnix101 yes - good catch.
The reason it fails is I forgot to split the group name and only check the actual group name, not including the container.

**Review by dnix101 — APPROVED** [review]
shipit

**Pull request merged**
