### PR TITLE
Add support deletion of snapshots from an offload target protection group

### PR DESCRIPTION
**Pull request by sdodsley**
##### SUMMARY
Add feature to be able to delete snapshots on offload target protection groups.
Also, fix a stylist error with a variable name

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
purefa_pgsnap.py
purefa_snap.py

##### ADDITIONAL INFORMATION
Use the `on` parameter to specify the offload target name and ensure that the snapshot name
is of the format `<arrayname>:<pgname>` and a correct `suffix` is provided

### CODE REVIEW

**Comment by sdodsley** [comment]
@WormNRifle These modules are designed to work with Ansible collections. If you are using regular Ansible and replacing the upstream modules then this will happen.

**Comment by WormNRifle** [comment]
Understood. 

I will look into that.

Thank you.

**Comment by WormNRifle** [comment]
I pulled the project down via collections, swapped out the purefa_pgsnap.py file in the collection and reran my playbook.

I'm getting the following:

> "Unsupported parameters for (purefa_pgsnap) module: True Supported parameters include: api_token, apply_retention, eradicate, fa_url, name, now, overwrite, remote, restore, state, suffix, target"

**Comment by sdodsley** [comment]
@WormNRifle Ah - there is a typo in the examples `on` should be `offload`. I have just pushed a fix.

**Comment by WormNRifle** [comment]
So, can I assume the OFFLOAD_API check is the version the offload code that is installed on my pure array?

**Comment by sdodsley** [comment]
It is checking to ensure the version of Purity running on the array is high enough to support the Offload functionality.

**Comment by WormNRifle** [comment]
Thank you for that verification.

**Pull request merged**
